### PR TITLE
Enable DNS server push

### PR DESCRIPTION
**Pull request by lmickh**
This has the potential to muck with people's DNS if they are relying on pointing to a non-public DNS server.  It would force them to use the AWS Route53 orgsync.com DNS servers while connected to the VPN.  Are we concerned about that being an issue?

### CODE REVIEW

**Comment by drywheat** [comment]
It would only use the Route53 DNS servers whenever the IP address is in one of the pushed routes (i.e. 10.0.1.0/24)? How could this cause an issue?

**Comment by lmickh** [comment]
It can't know to use the Route53 DNS unless it is already in the client's DNS settings.  This option tells the server to push the dhcp-option for DNS.  If the vpn client is configured by dhcp (which they all would be by default), it will put the Route53 server as their DNS.

**Comment by drywheat** [comment]
I read this on the help forum for the Viscosity OpenVPN client:

> It doesn't sound like the Apply DNS Settings Simultaneously option is what you are after here? It means that the DNS servers specified for the VPN connection will only be used for any domains also specified by the VPN connection. If this is in fact what you want, make sure that the necessary domains have been added to the Domains field (or are being pushed by the OpenVPN server). Without any domains listed the option will appear to have no effect.

To me, this indicates that we can restrict the use of Route53 DNS servers to a single domain, like **int.orgsync.com**.

image

**Comment by lmickh** [comment]
We can set the domain suffix list for the vpn connection.  Shouldn't hurt anything.  Not all vpn clients will configure split DNS though.  I'll update the branch with the change.

**Pull request merged**
